/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { useNavigate } from 'react-router-dom';
import { Button } from '@mui/material';


const Background = styled('div')({
  backgroundColor: `rgba(72, 191, 145, 1)`,
  borderRadius: `5px`,
  width: `200px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});


function ButtonPrimary(props) {


    const navigate = useNavigate();
    const routingHandler = () => {
      console.log("HI");
    
      navigate(`/${props.endPoint}`);
    } 
  
  return (
  
              <Button style={{  width: `200px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  width:`${props.width}`,
  top: `${props.topMargin}`,backgroundColor:'rgba(72, 191, 145, 1)',color:"white"}} onClick={routingHandler} >{props.title}</Button>
  );
}

export default ButtonPrimary;
