/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import CoverImage from 'src/assets/images/contentcarditem5_cover.png';

const ContentCardItem51 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `5px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
  width: 'fit-content',
});

const Media = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `245px`,
  height: `260px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Cover = styled('div')({
  backgroundImage: `url(${CoverImage})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  border: `1px solid rgba(221, 221, 221, 1)`,
  boxSizing: `border-box`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `245px`,
  height: `260px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const CardContent1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `25px 50px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
});

const H6 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(189, 189, 189, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0.20000000298023224px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  margin: `0px`,
}));

const H3 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(37, 43, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0.10000000149011612px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `15px 0px 0px 0px`,
}));

const Paragraph = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(133, 133, 133, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0.20000000298023224px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  margin: `15px 0px 0px 0px`,
}));

const Tags = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `15px 0px 0px 0px`,
  overflow: `hidden`,
});

const H61 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(35, 166, 240, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0.20000000298023224px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  margin: `0px`,
}));

const H62 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(35, 166, 240, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0.20000000298023224px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  margin: `0px 0px 0px 15px`,
}));

function ContentCardItem5(props) {
  return (
    <ContentCardItem51 className={props.className}>
      <Media>
        <Cover></Cover>
      </Media>
      <CardContent1>
        <H6>{`20 JAN 2023`}</H6>
        <H3>{`Start-up 1`}</H3>
        <Paragraph>
          {`Slate helps you see how many more days 
work to reach.`}
        </Paragraph>
        <Tags>
          <H61>{`Donate`}</H61>
          <H62>{`More`}</H62>
        </Tags>
      </CardContent1>
    </ContentCardItem51>
  );
}

export default ContentCardItem5;
