/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import BackgroundRemovebgPrImage from 'src/assets/images/Homepage_Background_removebg_preview_1.png';
import Image202303012259237Image from 'src/assets/images/Homepage_image_2023_03_01_225923788_removebg_preview_1.png';
import { styled } from '@mui/material/styles';
import ButtonPrimary from "./ButtonPrimary";
import { useNavigate } from 'react-router-dom';


const Homepage1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.3)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `700px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Background = styled('div')({
  backgroundColor: `rgba(0, 118, 190, 1)`,
  width: `1440px`,
  height: `700px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Content = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `399px`,
  height: `357px`,
  left: `118px`,
  top: `251px`,
});

const ButtonPrimary1 = styled(ButtonPrimary)(({ theme }) => ({
  width: `200px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `297px`,
}));

const TitleSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(139, 217, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `56px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const TitleSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(139, 217, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `36px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Title = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(139, 217, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `399px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Title1Span1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(139, 217, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `56px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Title1Span2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(139, 217, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `36px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const Title1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(139, 217, 199, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  textTransform: `none`,
  textShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  width: `399px`,
  position: `absolute`,
  left: `118px`,
  top: `251px`,
});

const BackgroundRemovebgPr = styled('img')({
  height: `575px`,
  width: `610px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `730px`,
  top: `62px`,
});

const Image202303012259237 = styled('img')({
  height: `188px`,
  width: `627px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `5px`,
  top: `62px`,
});

function Homepage(props) {

// const navigate = useNavigate();
// const routingHandler = () => {

//   navigate('/landing');
// } 
  return (
    <Homepage1 className={props.className}>
      <Background></Background>
      <Content>
        <ButtonPrimary endPoint={'landing'} topMargin={'297px'} title={"Lets Venture"}/>
        {/* <Button style={{  width: `200px`,
  height: `60px`,
  position: `absolute`,
  left: `0px`,
  top: `297px`,backgroundColor:'lightgreen'}} >Let's Venture</Button> */}
        <Title>
          <TitleSpan1>{`Cultivating Creativity: `}</TitleSpan1>
          <TitleSpan2>{`Helping Start-ups Thrive `}</TitleSpan2>
        </Title>
      </Content>
      <Title1>
        <Title1Span1>{`Cultivating Creativity: `}</Title1Span1>
        <Title1Span2>{`Helping Start-ups Thrive `}</Title1Span2>
      </Title1>
      <BackgroundRemovebgPr
        src={BackgroundRemovebgPrImage}
        loading="lazy"
        alt={'Background-removebg-preview 1'}
      />
      <Image202303012259237
        // src={props.imageName}
        loading="lazy"
        // alt={'image_2023-03-01_225923788-removebg-preview 1'}
      />
    </Homepage1>
  );
}

export default Homepage;
