/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Image202303012246016Image from 'src/assets/images/NavBarUserLandingPage_image_2023_03_01_224601648_removebg_preview_3.png';
import { styled } from '@mui/material/styles';
import ButtonPrimary from './ButtonPrimary';
import { width } from '@mui/system';

const NavBarUserLandingPag = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `86.22px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

// const Background = styled('div')({
//   backgroundColor: `rgba(0, 118, 190, 1)`,
//   width: `1440px`,
//   height: `86.22px`,
//   position: `absolute`,
//   left: `0px`,
//   top: `0px`,
// });

const ButtonPrimary1 = styled(ButtonPrimary)(({ theme }) => ({
  width: `276px`,
  height: `54px`,
  position: `absolute`,
  left: `1117px`,
  top: `16px`,
}));

const Links = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `161.72px`,
  height: `42px`,
  left: `937px`,
  top: `22px`,
});

const Frame45 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `0px`,
});

const Link1 = styled('div')({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
  display:`flex`,
  justifyContent:`flex-end`
});

const Link2 = styled('div')({
  textAlign: `right`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `51.72px`,
  position: `absolute`,
  left: `300px`,
  top: `10px`,
});

// const Image202303012246016 = styled('img')({
//   height: `72.75px`,
//   width: `327px`,
//   objectFit: `cover`,
//   position: `absolute`,
//   left: `17px`,
//   top: `6px`,
// });
const logoStyle={
   height: `72.75px`,
  width: `327px`,
  objectFit: `cover`,
  left: `17px`,
  top: `6px`, 
}

function NavBarUserLandingPage(props) {
  return (

    <div style={{display:"flex", flexDirection:"row",justifyContent:"space-between",backgroundColor: `rgba(0, 118, 190, 1)`,width:"100%"}}>


      {/* <Links>
        <Frame45>
          <Link1>{`About us`}</Link1>
        </Frame45>
        <Link2>{`Help`}</Link2>
      </Links> */}
      {/* <Image202303012246016
        src={Image202303012246016Image}
        loading="lazy"
        alt={'image_2023-03-01_224601648-removebg-preview 3'}
      /> */}
      <img src={Image202303012246016Image} style={logoStyle}></img>
      <div style={{display:"felx",flexDirection:"row",}}>
          <div style={{height:"50px",width:"50px",color:"white"}}>
        About Us
      </div>
      <div style={{height:"50px",width:"50px",color:"white"}}>
        Help
      </div>
      </div>
      </div>

  );
}

export default NavBarUserLandingPage;
