/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import InkpxWordArt11Image from 'src/assets/images/Navbar_inkpx_word_art__1__1.png';
import { styled } from '@mui/material/styles';
import ButtonPrimary from './ButtonPrimary';

const Navbar1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `86.22px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Background = styled('div')({
  backgroundColor: `rgba(0, 118, 190, 1)`,
  width: `1440px`,
  height: `86.22px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const ButtonPrimary1 = styled(ButtonPrimary)(({ theme }) => ({
  width: `140px`,
  height: `53.89px`,
  position: `absolute`,
  left: `1260px`,
  top: `16px`,
}));

const Links = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `175px`,
  height: `22px`,
  left: `1045px`,
  top: `31px`,
});

const Link1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Link2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `61px`,
  top: `0px`,
});

const Link3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `130px`,
  top: `0px`,
});

const InkpxWordArt11 = styled('img')({
  height: `29px`,
  width: `162px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `9px`,
  top: `17px`,
});

function Navbar(props) {
  return (
    <Navbar1 className={props.className}>
      <Background></Background>
      {false && <ButtonPrimary1 />}
      {false && (
        <Links>
          <Link1>{`API`}</Link1>
          <Link2>{`Help`}</Link2>
          <Link3>{`Login`}</Link3>
        </Links>
      )}
      {false && (
        <InkpxWordArt11
          src={InkpxWordArt11Image}
          loading="lazy"
          alt={'inkpx-word-art (1) 1'}
        />
      )}
    </Navbar1>
  );
}

export default Navbar;
