/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Homepage from 'src/components/Homepage/Homepage';
import ContentCardItem5 from './ContentCardItem5';
import NavBarUserLandingPage from './NavBarUserLandingPage';

const UserLandingPage1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `943px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Page2 = styled(Homepage)(({ theme }) => ({
  width: `1440px`,
  height: `943px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const ContentCardItem51 = styled(ContentCardItem5)(({ theme }) => ({
  position: `absolute`,
  left: `375px`,
  top: `135px`,
}));

const NavbarBere = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `-0.17600000381469727px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `515px`,
  height: `83px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const ContentCardItem52 = styled(ContentCardItem5)(({ theme }) => ({
  position: `absolute`,
  left: `375px`,
  top: `416px`,
}));

const ContentCardItem53 = styled(ContentCardItem5)(({ theme }) => ({
  height: `237px`,
  position: `absolute`,
  left: `375px`,
  top: `697px`,
}));


function UserLandingPage(props) {
  return (
    <UserLandingPage1 className={props.className}>
      {/* <Page2 /> */}
      <ContentCardItem51 />
      {/* <NavbarBere>
        {`Navbar Bere
`}
      </NavbarBere> */}
      <NavBarUserLandingPage />
      
      <ContentCardItem52 />
      <ContentCardItem53 />

    </UserLandingPage1>
  );
}

export default UserLandingPage;
